//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions  } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import { Client as ClientClass } from '../axios-client';
import { createClient, getClientFactory } from './helpers';

export const Client = () => getClientFactory()(ClientClass);
import type { AxiosRequestConfig } from 'axios';

    
export function vtubersUrl(): string {
  let url_ = getBaseUrl() + "/api/Twitch/vtubers";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let vtubersDefaultOptions: UseQueryOptions<Types.DTVTuber[], unknown, Types.DTVTuber[]> = {
  queryFn: __vtubers,
};
export function getVtubersDefaultOptions(): UseQueryOptions<Types.DTVTuber[], unknown, Types.DTVTuber[]> {
  return vtubersDefaultOptions;
};
export function setVtubersDefaultOptions(options: UseQueryOptions<Types.DTVTuber[], unknown, Types.DTVTuber[]>) {
  vtubersDefaultOptions = options;
}

export function vtubersQueryKey(): QueryKey;
export function vtubersQueryKey(...params: any[]): QueryKey {
  return trimArrayEnd([
      'Client',
      'vtubers',
    ]);
}
function __vtubers() {
  return Client().vtubers(
    );
}

/**
 * @return Success
 */
export function useVtubersQuery<TSelectData = Types.DTVTuber[], TError = unknown>(options?: UseQueryOptions<Types.DTVTuber[], TError, TSelectData>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useVtubersQuery<TSelectData = Types.DTVTuber[], TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.DTVTuber[], TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined;
  

  options = params[0] as any;
  axiosConfig = params[1] as any;

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  if (axiosConfig) {
    options = options ?? { } as any;
    options!.meta = { ...options!.meta, axiosConfig };
  }

  return useQuery<Types.DTVTuber[], TError, TSelectData>({
    queryFn: __vtubers,
    queryKey: vtubersQueryKey(),
    ...vtubersDefaultOptions as unknown as UseQueryOptions<Types.DTVTuber[], TError, TSelectData>,
    ...options,
  });
}
/**
 * @return Success
 */
export function setVtubersData(queryClient: QueryClient, updater: (data: Types.DTVTuber[] | undefined) => Types.DTVTuber[], ) {
  queryClient.setQueryData(vtubersQueryKey(),
    updater
  );
}

/**
 * @return Success
 */
export function setVtubersDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.DTVTuber[] | undefined) => Types.DTVTuber[]) {
  queryClient.setQueryData(queryKey, updater);
}