//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions  } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import { SevenTvClient as SevenTvClientClass } from '../axios-client';
import { createClient, getClientFactory } from './helpers';

export const Client = () => getClientFactory()(SevenTvClientClass);
import type { AxiosRequestConfig } from 'axios';

export type EmotesSevenTvQueryParameters = {
  broadcasterId: number | undefined;
};

    
export function emotesUrl(broadcasterId: number | undefined): string {
  let url_ = getBaseUrl() + "/api/SevenTv/emotes?";
if (broadcasterId === null)
    throw new Error("The parameter 'broadcasterId' cannot be null.");
else if (broadcasterId !== undefined)
    url_ += "broadcasterId=" + encodeURIComponent("" + broadcasterId) + "&";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let emotesDefaultOptions: UseQueryOptions<Types.DTEmote[], unknown, Types.DTEmote[]> = {
  queryFn: __emotes,
};
export function getEmotesDefaultOptions(): UseQueryOptions<Types.DTEmote[], unknown, Types.DTEmote[]> {
  return emotesDefaultOptions;
};
export function setEmotesDefaultOptions(options: UseQueryOptions<Types.DTEmote[], unknown, Types.DTEmote[]>) {
  emotesDefaultOptions = options;
}

export function emotesQueryKey(broadcasterId: number | undefined): QueryKey;
export function emotesQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { broadcasterId,  } = params[0] as EmotesSevenTvQueryParameters;

    return trimArrayEnd([
        'SevenTvClient',
        'emotes',
        broadcasterId as any,
      ]);
  } else {
    return trimArrayEnd([
        'SevenTvClient',
        'emotes',
        ...params
      ]);
  }
}
function __emotes(context: QueryFunctionContext) {
  return Client().emotes(
      context.queryKey[2] as number | undefined    );
}

export function useEmotesQuery<TSelectData = Types.DTEmote[], TError = unknown>(dto: EmotesSevenTvQueryParameters, options?: UseQueryOptions<Types.DTEmote[], TError, TSelectData>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * @param broadcasterId (optional) 
 * @return Success
 */
export function useEmotesQuery<TSelectData = Types.DTEmote[], TError = unknown>(broadcasterId: number | undefined, options?: UseQueryOptions<Types.DTEmote[], TError, TSelectData>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useEmotesQuery<TSelectData = Types.DTEmote[], TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.DTEmote[], TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined;
  let broadcasterId: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ broadcasterId,  } = params[0] as EmotesSevenTvQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [broadcasterId, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  if (axiosConfig) {
    options = options ?? { } as any;
    options!.meta = { ...options!.meta, axiosConfig };
  }

  return useQuery<Types.DTEmote[], TError, TSelectData>({
    queryFn: __emotes,
    queryKey: emotesQueryKey(broadcasterId),
    ...emotesDefaultOptions as unknown as UseQueryOptions<Types.DTEmote[], TError, TSelectData>,
    ...options,
  });
}
/**
 * @param broadcasterId (optional) 
 * @return Success
 */
export function setEmotesData(queryClient: QueryClient, updater: (data: Types.DTEmote[] | undefined) => Types.DTEmote[], broadcasterId: number | undefined) {
  queryClient.setQueryData(emotesQueryKey(broadcasterId),
    updater
  );
}

/**
 * @param broadcasterId (optional) 
 * @return Success
 */
export function setEmotesDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.DTEmote[] | undefined) => Types.DTEmote[]) {
  queryClient.setQueryData(queryKey, updater);
}